### 数据源
spring.datasource.platform=MSSQL
spring.datasource.url=jdbc:jtds:sqlserver://49.233.127.141:1433/ccflowdb1;DatabaseName=ccflowdb1;useLOBs=false
spring.datasource.name=ccflowdb1
spring.datasource.username=sa
spring.datasource.password=ccflow@2022
spring.datasource.driver-class-name=net.sourceforge.jtds.jdbc.Driver
spring.datasource.hikari.connection-test-query=select 'a'
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=180000
