import { reactive } from 'vue';
const menuList = reactive([
  {
    key: 1,
    Name: '功能页面集成',
    GroupName: '前端用户操作',
    Icon: 'icon-user',
    Path: '/Common',
    IsShow: 1,
    children: [
      {
        key: 101,
        No: 'GL_Start',
        Name: '发起',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=GL_Start',
        Icon: 'icon-paper-plane',
        Enable: 1,
      },
      {
        key: 102,
        No: 'GL_Todolist',
        Name: '待办',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=GL_Todolist',
        Icon: 'icon-clock',
        Enable: 1,
      },
      {
        key: 103,
        No: 'GL_Runing',
        Name: '在途',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Paras: 'DoWhat=Component&EnName=GL_Runing',
        Path: 'Port',
        Icon: 'icon-hourglass',
        Enable: 1,
      },
      {
        key: 104,
        No: 'GL_RecentWork',
        Name: '近期',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Paras: 'DoWhat=Component&EnName=GL_RecentWork',
        Path: 'Port',
        Icon: 'icon-envelope',
        Enable: 1,
      },
      {
        key: 105,
        No: 'GL_CC',
        Name: '抄送',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Paras: 'DoWhat=Component&EnName=GL_CC',
        Path: 'Port',
        Icon: 'icon-bag',
        Enable: 1,
      },
      {
        key: 106,
        No: 'GL_Draft',
        Name: '草稿',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=GL_Draft',
        Icon: 'icon-note',
        Enable: 1,
      },
      {
        key: 301,
        No: 'TS.FlowData.GenerWorkFlowView',
        Name: '综合查询',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=EntitySearch&EnName=TS.FlowData.GenerWorkFlowView',
        Icon: 'icon-magnifier',
        Enable: 1,
      },
      {
        key: 107,
        No: 'GL_Msg',
        Name: '消息',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=GL_Msg',
        Icon: 'icon-bubbles',
        Enable: 0,
      },
      //高代码/低代码 - 组件
      // {
      //   key: 108,
      //   No: 'Port高代码查询',
      //   Name: '高代码查询',
      //   FileUrl: '/src/views/portPage/CommonPort.vue',
      //   Path: 'Port',
      //   Paras: 'DoWhat=EntitySearch&EnName=TS.Demo.Student',
      //   Icon: FieldTimeOutlined,
      //   Enable: 1,
      // },
      // {
      //   key: 109,
      //   No: 'Port低代码SearchNoName',
      //   Name: '低代码SearchNoName',
      //   FileUrl: '/src/views/portPage/CommonPort.vue',
      //   Path: 'Port',
      //   Paras: 'DoWhat=EntityNoName&FrmID=Entity_CheLiangWeiXiu',
      //   Icon: FieldTimeOutlined,
      //   Enable: 1,
      // },
      // {
      //   key: 110,
      //   No: 'Port单据SearchBill',
      //   Name: '单据SearchBill',
      //   FileUrl: '/src/views/portPage/CommonPort.vue',
      //   Path: 'Port',
      //   Paras: 'DoWhat=EntityBill&FrmID=Bill_WeiXiuDanJu',
      //   Icon: FieldTimeOutlined,
      //   Enable: 1,
      // },
      // 轨迹图组件
      // {
      //   key: 111,
      //   No: '轨迹图',
      //   Name: '轨迹图',
      //   FileUrl: '/src/views/portPage/CommonPort.vue',
      //   Path: 'Port',
      //   Paras: 'DoWhat=Vue3Track&FK_Flow=097&WorkID=692',
      //   Icon: FieldTimeOutlined,
      //   Enable: 0,
      // },
      // GPN_
      // {
      //   key: 112,
      //   No: 'GPN_ImpOrg',
      //   Name: 'GPN导入',
      //   FileUrl: '/src/views/portPage/CommonPort.vue',
      //   Path: 'Port',
      //   Paras: 'DoWhat=Component&EnName=GPN_ImpOrg',
      //   Icon: FieldTimeOutlined,
      //   Enable: 1,
      // },
  ],
  },
  // {
  //   key:2,
  //   Name: '前端单流程',
  //   GroupName: '前端单流程',
  //   Icon: AppstoreOutlined,
  //   Path: '/Common',
  //   children: [
  //     {
  //       key: 201,
  //       No: '查询FlowNo=002',
  //       Name: '单流程查询(002)',
  //       FileUrl: '/src/views/portPage/CommonPort.vue',
  //       Path: 'Port',
  //       Paras: 'DoWhat=SearchFlow&FlowNo=002',
  //       Icon: FieldTimeOutlined,
  //       Enable: 1,
  //     },
  //     {
  //       key: 202,
  //       No: '发起FlowNo=002',
  //       Name: '单流程发起(002)',
  //       FileUrl: '/src/views/portPage/CommonPort.vue',
  //       Path: 'Port',
  //       Paras: 'DoWhat=StartFlow&FlowNo=002',
  //       Icon: FieldTimeOutlined,
  //       Enable: 1,
  //     },
  //     // {
  //     //   key: 201,
  //     //   No: 'Port单流程查询FlowNo=002',
  //     //   Name: '单流程查询(002)',
  //     //   FileUrl: '/src/views/portPage/CommonPort.vue',
  //     //   Path: 'Port',
  //     //   Paras: 'DoWhat=SearchFlow&FlowNo=204',
  //     //   Icon: FieldTimeOutlined,
  //     //   Enable: 1,
  //     // },
  //     // {
  //     //   key: 202,
  //     //   No: 'Port单流程发起FlowNo=002',
  //     //   Name: '单流程发起(002)',
  //     //   FileUrl: '/src/views/portPage/CommonPort.vue',
  //     //   Path: 'Port',
  //     //   Paras: 'DoWhat=StartFlow&FlowNo=204',
  //     //   Icon: FieldTimeOutlined,
  //     //   Enable: 1,
  //     // },
  //     {
  //       key: 203,
  //       No: '处理/查看',
  //       Name: '处理/查看',
  //       FileUrl: '/src/views/portPage/CommonPort.vue',
  //       Path: 'Port',
  //       Paras: 'DoWhat=MyView&FlowNo=097&WorkID=699',
  //       Icon: FieldTimeOutlined,
  //       Enable: 1,
  //     },
  //     {
  //       key: 204,
  //       No: '抄送002',
  //       Name: '抄送',
  //       FileUrl: '/src/views/portPage/CommonPort.vue',
  //       Path: 'Port',
  //       Paras: 'DoWhat=MyCC&FlowNo=097&WorkID=692',
  //       Icon: FieldTimeOutlined,
  //       Enable: 1,
  //     },
  //   ],
  // },
  // {
  //   key: 3,
  //   Name: '流程查询',
  //   GroupName: '流程查询',
  //   Icon: AppstoreOutlined,
  //   Path: '/Common',
  //   children: [
  //     {
  //       key: 301,
  //       No: 'TS.FlowData.GenerWorkFlowView',
  //       Name: '综合查询',
  //       FileUrl: '/src/views/portPage/CommonPort.vue',
  //       Path: 'Port',
  //       Paras: 'DoWhat=EntitySearch&EnName=TS.FlowData.GenerWorkFlowView',
  //       Icon: FieldTimeOutlined,
  //       Enable: 1,
  //     },
  //   ],
  // },
  {
    key: 4,
    Name: 'Admin应用设计',
    GroupName: 'Admin应用设计',
    Icon: 'icon-settings',
    Path: '/Common',
    IsShow: 1,
    children: [
      {
        key: 401,
        No: 'TreeEns_FlowSort2Flow',
        Name: '流程',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=TreeEns_FlowSort2Flow',
        Icon: 'icon-organization',
        Enable: 1,
      },
      {
        key: 402,
        No: 'TreeEns_FrmSort2Frm',
        Name: '表单',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=TreeEns_FrmSort2Frm',
        Icon: 'icon-diamond',
        Enable: 1,
      },
      {
        key: 403,
        No: 'TreeEns_Dept2Emp',
        Name: '组织',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=TreeEns_Dept2Emp',
        Icon: 'icon-people',
        Enable: 1,
      },
      {
        key: 404,
        No: 'TreeEns_DBSrc',
        Name: '数据源',
        FileUrl: '/src/views/portPage/CommonPort.vue',
        Path: 'Port',
        Paras: 'DoWhat=Component&EnName=TreeEns_DBSrc',
        Icon: 'icon-settings',
        Enable: 1,
      },
    ],
  },
]);

export default menuList;
